backend:
  name: github
  repo: porfirioribeiro/quintadaspoesias
  branch: develop
  squash_merges: true

media_folder: 'static/files/images'
public_folder: '/files/images'

# publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'home'
    label: 'Homepage'
    folder: 'src/content/home'
    create: true
    slug: '{{language}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'homepage' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: [{ value: 'en', label: 'English' }, { value: 'pt', label: 'Portugês' }],
          default: 'en',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: [{ value: 'en', label: 'English' }, { value: 'pt', label: 'Portugês' }],
          default: 'en',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
  - name: 'brand'
    label: 'Marca'
    folder: 'src/content/brand'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'brand-page' }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'path', widget: 'string', defaukt: '{{slug}}' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'product'
    label: 'Produto'
    folder: 'src/content/product'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'brand-page' }
      - {
          label: 'Marca',
          name: 'brand',
          widget: 'relation',
          collection: 'brand',
          searchFields: ['title'],
          valueField: 'title',
          displayFields: ['title'],
        }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
